---
title: Exceptions and Errors Continued
date: 2018-04-25
description:
  Continuation of a discussion of Java errors and error handling.
spelling_exceptions:
  - dereferenced
  - incentivize
  - recursed
  - rethrow
  - Rethrowing
echo: https://goo.gl/zGieMx
---
:imagesdir: /learn/images

[[QvnzLXdQHdksGlXPpcJDmjidkjBtRjek]]
== !

[.janini.smaller]
--
++++
<div class="message">Exceptions and Errors Continued</div>
++++
....
static void throwError() throws Exception {
  throw new Exception("Exceptions and Errors Continued");
}

try {
  throwError();
} catch (Exception e) {
  System.out.println(e);
}
....
--

[[nbmxbUangABLUEHOCwqeRuKpLzOAqZQd]]
== ! Q11 Review and Warmup

[.janini.compiler.smallest]
....
import java.util.Arrays;

/**
 * Class for storing the last ten integers added.
 *
 * Your class should be named LastTen.
 *
 * Your class should implement two public methods as described below:
 * 1. void add(int newValue):
 *    add a new integer to the values that we are rememebring
 * 2. int[] getLastTen():
 *    return the last ten values that were added using add, in any order.
 *    If fewer than ten values were added, you should return zeros in their
 *    place.
 *
 * Examples:
 *   1. add(1), add(2)
 *      getLastTen: [1, 2, 0, 0, 0, ... ]
 *   2. add(0), add(1), add(2), ... add(10)
 *      getLastTen: [1, 2, 3, 4, ... 10]
 *
 * Your class should also provide a constructor that takes no arguments.
 */

public class Example {
  public static void main(final String[] unused) {
    LastTen lastTen = new LastTen();
    for (int i = 0; i < 20; i++) {
      lastTen.add(i);
    }
    System.out.println(Arrays.toString(lastTen.getLastTen()));
  }
}
....

[[NgSMAwsMTdJArBYXQLnHeUxhTHnfkOWO]]
[.oneword]
//
== Exceptions
//
Because things go wrong...

[[aGPxoRnNcYNYDrkciLIXCQtcfauqstFG]]
== Exceptional Control Flow

[.lead]
//
When an error is thrown control flow _immediately_ jumps to an
enclosing `catch` statement, if one exists.

The `catch` may be in the caller or multiple levels up.

[source,java,role='smallest']
----
static void foo1() {
  Object it = null;
  int hash = it.hashCode();
}
static void foo2() {
  foo1();
}
static void foo3() {
  foo2();
}
static void foo4() {
  try {
    foo3();
  } catch (Exception e) {
  }
}
----

[[SeOQGYKwsgXdStZpbnLyKXRzcnodvdkg]]
== ! `try-catch` with Functions Example


[.janini.smaller]
....
static void foo1() {
  Object it = null;
  int hash = it.hashCode();
}
static void foo2() {
  foo1();
}
static void foo3() {
  foo2();
}
static void foo4() {
  try {
    foo3();
  } catch (Exception e) {
  }
}
foo4();
....


[[hHpJlOjfMZHLDFIEtYEVveZKGChYtAoT]]
== Types of Exceptions

[.lead]
//
Java exceptions are broken into three distinct categories:

[.s]
//
* *Checked exceptions*: these are for places where you _know_ something might go
wrong and it's out of your control
//
* *Unchecked exceptions* (or runtime errors): these are usually caused by
something dumb that you (the programmer) did wrong
//
* *Errors*: these are reserved for serious system problems that are probably not
recoverable

[[mDntiMShclykEeTHFbbcWpaIaMDOtslB]]
== Checked Exceptions: Handling

[.lead]
//
If you use a function that may generate a checked exception, you must either
wrap it in a `try-catch` block or declare that you may throw it.

[source,role='s smaller']
----
static URI createURI(final String input) {
  // Example where we handle URISyntaxExceptions
  try {
    return new URI(input);
  } catch (URISyntaxException e) {
    System.out.println(input + " is not a valid URI");
  }
}
----

[source,role='s smaller mt-2']
----
// Example where we throw URISyntaxExceptions
static URI createURI(final String input) throws URISyntaxException {
  return new URI(input);
}
----

[[fQksWEmXdgBjncevNfmiwEpQtfJUdBqp]]
== Unchecked Exceptions: Examples

[.lead]
//
Unchecked examples are usually the result of _programmer error_.

You've probably made many of these mistakes by now...

[.s.small]
//
* https://docs.oracle.com/javase/7/docs/api/java/lang/ArrayIndexOutOfBoundsException.html[`ArrayIndexOutOfBoundsException`]:
//
[.s]#you walked off the end of an array#
//
* https://docs.oracle.com/javase/7/docs/api/java/lang/NullPointerException.html[`NullPointerException`]:
//
[.s]#you dereferenced a `null` reference#
//
* https://docs.oracle.com/javase/7/docs/api/java/lang/ClassCastException.html[`ClassCastException`]:
//
[.s]#you tried to cast something to a subclass of which it is not an instance#
//
* https://docs.oracle.com/javase/7/docs/api/java/lang/IllegalArgumentException.html[`IllegalArgumentException`]:
//
[.s]#you passed incorrect arguments to a function or constructor#

[[ISJDepXiVBpgjPhbyHGqeRxQaBOzKVBD]]
== ! Unchecked Exceptions: Examples

[.janini.smaller]
....
import java.util.Arrays;

static void faulter() {
}
try {
  faulter();
} catch (ArrayIndexOutOfBoundsException e) {
  System.out.println("Whoops!");
} catch (NullPointerException e) {
  System.out.println("Oh, no!");
} catch (ClassCastException e) {
  System.out.println("That's too bad...");
} catch (IllegalArgumentException e) {
  System.out.println("Don't do that!");
}
....

[[JeobqXuXzWOKfLNYVANnZhhpASBkdiJz]]
== ! Arrays Again

++++
<div class="embed-responsive embed-responsive-4by3">
  <iframe class="full embed-responsive-item" src="https://docs.oracle.com/javase/7/docs/api/java/util/Arrays.html"></iframe>
</div>
++++

[[JoSAhTRGjusouJkDfQshuUUDdlPlJWEs]]
== Unchecked Exceptions: Handling

[.lead]
//
Unlike checked exceptions, you do not need to declare or handle unchecked
exceptions.

However, you _can_ handle them:

[source,java,role='s smaller']
----
try {
  String s = callMyPartnersDodgyCode();
  if (s.length() == 0) {
    return;
  }
} catch (NullPointerException e) {
  return;
}
----

[[kQbOfdZFwWMQsOQmhbBQogCUGHympVWJ]]
== Errors: Examples

[.lead]
//
Java errors indicate serious conditions that are usually not recoverable:

[.s]
//
* https://docs.oracle.com/javase/7/docs/api/java/lang/OutOfMemoryError.html[`OutOfMemoryError`]:
//
Java ran out of memory and is going to crash
//
* https://docs.oracle.com/javase/7/docs/api/java/lang/StackOverflowError.html[`StackOverflowError`]:
//
You recursed too deeply and Java is going to crash
//
* Note that sometimes _these are still your fault_: you used too much memory or
forgot your base case

[[ajpSqxeufhVlXQkgrigFcjuJqXwzCANS]]
== Exception Handling Strategies

[.lead]
//
Here are reasonable strategies for handling each kind of exception:

[.s]
//
* *Errors*: _don't_ try to handle these, just go bye-bye
//
* *Unchecked exceptions*: try to _avoid_ these by improving your code
//
* *Checked exceptions*: try to handle these and have your program
continue running, or exit gracefully...
//
* but don't go on unless you can.

[[RoxnUIFqZCBrBZnusOrpzbLuksmJMpdG]]
== Working with Exceptions

[.lead]
//
Java exceptions are just another kind of Java object&mdash;and they have some
useful features, particularly when debugging:

[.s]
//
* `toString`: like every other Java `Object`, exceptions can be printed
//
* `getMessage`: retrieves just the message associated with this exception
//
* `printStackTrace`: print a _stack trace_ for the error showing what caused it
and what other functions were involved

[[wIAiKctczCEQFknYPSiRbruXLqBIGBMy]]
== !Throwable Documentation

++++
<div class="embed-responsive embed-responsive-4by3">
  <iframe class="full embed-responsive-item" src="https://docs.oracle.com/javase/7/docs/api/java/lang/Throwable.html"></iframe>
</div>
++++

[[zzlPSnhuaDjSgoGIAkpIjUQZeiuerNQe]]
== !Working with Exceptions Examples

[.janini.smaller]
....
static void foo1() {
  Object it = null;
  int hash = it.hashCode();
}
static void foo2() {
  foo1();
}
static void foo3() {
  foo2();
}
static void foo4() {
  try {
    foo3();
  } catch (Exception e) {
  }
}
foo4();
....

[[CTsKSqiFCfFyikLMwtUmDbmSXijFayAL]]
== Rethrowing Exceptions

[.lead]
//
Sometimes you may want to just record what happened but not know what to do with
an error.

In that case you may want to rethrow it out of the catch block:

[source,role='smaller']
----
static URI createURI(final String input) {
  // Example where we handle URISyntaxExceptions
  try {
    return new URI(input);
  } catch (URISyntaxException e) {
    // Log that something went wrong
    Log.e(TAG, input + " is not a valid URI");
    // Rethrow the exception
    throw(e);
  }
}
----

[[diIiwLksuhFzuaiuxOuRIZnfIpgBPFnP]]
== Throwing Your Own Exceptions

[.lead]
//
So how do we handle a case like this?

[source,java]
----
class StringStorage {
  /**
   * Create a new object to store strings.
   *
   * @param storageSize the size of the StringStorage,
   *        must be positive
   */
  public StringStorage(final int storageSize) {
    if (storageSize <= 0) {
      // what now?
    }
  }
}
----

[[tZEORkretvixoGRTiPQxDkXOhkrgdAUE]]
== ! Throwing Your Own Exceptions

[.janini.smaller.compiler]
....
public class StringStorage {
  /**
   * Create a new object to store strings.
   *
   * @param storageSize the size of the StringStorage,
   *        must be positive
   */
  public StringStorage(final int storageSize) {
    if (storageSize <= 0) {
      // what now?
    }
  }
}
public class Example {
  public static void main(final String[] unused) {
    StringStorage stringStorage = new StringStorage(-1);
  }
}
....

[[TyzTkvyjvmKDPkZwmxwufvXMjajIlrHV]]
== `throw`

[.lead]
//
To throw an exception in Java we use the `throw` keyword:

[source,java]
----
Exception e = new Exception("you did something awful");
throw(e);
----

[[qoTmuDmRuBRgiUxPONZaOVhCRmlElcLw]]
== `throw` Well

[.lead]
//
If you need to throw an exception:

[.s]
//
* Look for an existing `Exception` class that's a good fit
//
* Or, create your own:

[source,java,role='s smaller']
----
public class MyException extends Exception {
}
throw(new MyException("bad bad"));
----

[[SRZEFPcrGpKfBdzGREcjDZALhTbKaIsC]]
== `finally`

[.lead]
//
Java's `try-catch` also supports a `finally` block. It is _always_ executed after
_either_ the `try` or the `catch` completes:

[source,java,role='smaller']
----
try {
  System.out.println("start");
  couldError();
  System.out.println("done");
} catch (Exception e) {
  System.out.println("catch");
} finally {
  System.out.println("finally");
}
----

[[mhmYjmPPucLHcPEFfhzCtQfFbnqfuYjZ]]
== ! `finally` Example

[.janini.smaller]
....
import java.util.Random;

static void couldError() {
  Random random = new Random();
  if (random.nextBoolean()) {
    Object it = null;
    it.hashCode();
  }
}

try {
  System.out.println("start");
  couldError();
  System.out.println("done");
} catch (Exception e) {
  System.out.println("catch");
} finally {
  System.out.println("finally");
}
....

[[eZOQBRhCvuQhjkIrABjfwolqygMADAfE]]
== Intelligent `try` Usage

[.lead]
//
You can make intelligent use of `try-catch` blocks to avoid repetitive sanity
checking:

[source,java,role='smaller']
----
JsonParser parser = new JsonParser();
JsonObject info = parser.parse(json).getAsJsonObject();
if (!info.has("metadata")) {
  return 0;
}
JsonObject metadata = info.getAsJsonObject("metadata");
if (!metadata.has("width")) {
  return 0;
}
JsonElement width = metadata.getAsJsonElement("width");
return width.getAsInt();
----

[[PTcgGbrBNJAzQGjhIpXKlPnMXeUoxUmP]]
== Intelligent `try` Usage

[.lead]
//
You can make intelligent use of `try-catch` blocks to avoid repetitive sanity
checking:

(This is particularly nice when you can chain calls together.)

[source,java,role='smaller']
----
try {
  JsonParser parser = new JsonParser();
  return parser.parse(json)
    .getAsJsonObject()
    .getAsJsonObject("metadata")
    .get("width")
    .getAsInt();
} catch (Exception e) {
  return 0;
}
----

[[MOtQFFYNnjbBbeGMOidiZDswLFnfSKxo]]
== Announcements

* link:/MP/7/[MP7 (the final project)] is out.
//
Please get started!
//
* The
//
https://cs125.cs.illinois.edu/info/feedback/[anonymous feedback form]
//
remains available on the course website. Use it to give us feedback!
//
* My office hours continue today at 11AM in the lounge outside of Siebel 0226.

// vim: ts=2:sw=2:et
